repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.7
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
# https://stackoverflow.com/a/71662957
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.15.0
  hooks:
  - id: mypy
    additional_dependencies: [
          "shapely>=2.0",       # Shapely 2.0+ includes type hints
          "geopandas",          # Needed for geopandas imports
          # "types-shapely",      # Explicit stubs (recommended by your logs)
          # "types-geopandas"     # Explicit stubs for geopandas
        ]
    pass_filenames: false  # suppress the normal filename passing
    files: ^aasd/  # filter the files down to a specific subdirectory
    # pre-commit only supports running at the root of a repo since that's where
    # git hooks run.  but it also allows running arbitrary code so you can
    # step outside of those bounds
    # note that `bash` will reduce your portability slightly
    entry: bash -c 'cd aasd && uv run mypy src/aasd' --
    args: ["--config-file=pyproject.toml", "."]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: mixed-line-ending
